const shuffle = function(array) {
  console.log('--> Shuffling photos')
  var currentIndex = array.length, temporaryValue, randomIndex
  while (0 !== currentIndex) {
    randomIndex = Math.floor(Math.random() * currentIndex)
    currentIndex -= 1
    temporaryValue = array[currentIndex]
    array[currentIndex] = array[randomIndex]
    array[randomIndex] = temporaryValue
  }
  return array
}

const makeUsablePhotoArray = function(array, assetHost) {
  return array
    .filter(photo => photo.active)
    .map(photo => {
      photo.src = `${assetHost}/${photo.roll}+${photo.number}.jpg?2020010102`
      photo.alt = `${photo.subject}, ${photo.venue}, ${photo.date}`
      return photo
    })
}

const photos = [
  {
    "id": 1,
    "roll": "0014",
    "number": "E",
    "date": "2017-03-04",
    "subject": "Mykki Blanco",
    "active": 0,
    "venue": "The Independent",
    "city": "San Francisco",
    "format": "35mm",
    "film": "GC 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 2,
    "roll": "0019",
    "number": 20,
    "date": "2017-04-14",
    "subject": "FKJ",
    "active": 1,
    "venue": "The Warfield",
    "city": "San Francisco",
    "format": "35mm",
    "film": "GC 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 3,
    "roll": "0022",
    "number": "03",
    "date": "2017-04-21",
    "subject": "Travis Scott",
    "active": 0,
    "venue": "Coachella 2017",
    "city": "Indio",
    "format": "35mm",
    "film": "GC 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 4,
    "roll": "0027",
    "number": 10,
    "date": "2017-06-10",
    "subject": "XXXTENTACION",
    "active": 0,
    "venue": "Regency Ballroom",
    "city": "San Francisco",
    "format": "35mm",
    "film": "GC 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 5,
    "roll": "0047",
    "number": 24,
    "date": "2017-10-31",
    "subject": "Tyler, the Creator",
    "active": 1,
    "venue": "The Warfield",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 6,
    "roll": "0054",
    "number": 14,
    "date": "2017-11-27",
    "subject": "Syd",
    "active": 1,
    "venue": "Regency Ballroom",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 7,
    "roll": "0071",
    "number": 21,
    "date": "2018-01-12",
    "subject": "Big Boi",
    "active": 0,
    "venue": "1015 Folsom",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 8,
    "roll": "0079",
    "number": "07",
    "date": "2018-01-22",
    "subject": "St. Vincent",
    "active": 0,
    "venue": "Bill Graham Civic Auditorium",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 9,
    "roll": "0081",
    "number": 23,
    "date": "2018-01-29",
    "subject": "Tyler, the Creator",
    "active": 0,
    "venue": "The Armory",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Portra 400",
    "camera": "Contax T2",
    "comment": "Night 1"
  },
  {
    "id": 10,
    "roll": "0082",
    "number": 24,
    "date": "2018-01-30",
    "subject": "Tyler, the Creator",
    "active": 0,
    "venue": "The Armory",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Pro 400H",
    "camera": "Contax T2",
    "comment": "Night 2"
  },
  {
    "id": 11,
    "roll": "0098",
    "number": "02",
    "date": "2018-04-18",
    "subject": "Jonathan Davis, Korn",
    "active": 0,
    "venue": "The Fillmore",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 12,
    "roll": "0103",
    "number": 20,
    "date": "2018-04-30",
    "subject": "KILLY",
    "active": 0,
    "venue": "Brick & Mortar Music Hall",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 13,
    "roll": "0114",
    "number": 14,
    "date": "2018-05-13",
    "subject": "Anderson .Paak",
    "active": 0,
    "venue": "Middle Harbor Shoreline Park",
    "city": "Oakland",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 14,
    "roll": "0115",
    "number": 20,
    "date": "2018-05-13",
    "subject": "Migos",
    "active": 0,
    "venue": "Middle Harbor Shoreline Park",
    "city": "Oakland",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 15,
    "roll": "0129",
    "number": 23,
    "date": "2018-07-24",
    "subject": "Playboi Carti",
    "active": 1,
    "venue": "The Warfield",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 16,
    "roll": "0132",
    "number": 14,
    "date": "2018-08-10",
    "subject": "Billie Eilish",
    "active": 0,
    "venue": "Golden Gate Park",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 17,
    "roll": "0135",
    "number": 26,
    "date": "2018-08-11",
    "subject": "Mac Demarco",
    "active": 1,
    "venue": "The Independent",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 18,
    "roll": "0138",
    "number": 20,
    "date": "2018-08-12",
    "subject": "James Blake",
    "active": 1,
    "venue": "Golden Gate Park",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 19,
    "roll": "0147",
    "number": 32,
    "date": "2018-09-17",
    "subject": "Kali Uchis",
    "active": 0,
    "venue": "The Warfield",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 20,
    "roll": "0153",
    "number": 14,
    "date": "2018-10-09",
    "subject": "Alina Baraz",
    "active": 1,
    "venue": "The Warfield",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": "Night 1"
  },
  {
    "id": 21,
    "roll": "0163",
    "number": 16,
    "date": "2018-11-23",
    "subject": "Father",
    "active": 0,
    "venue": "The New Parish",
    "city": "Oakland",
    "format": "35mm",
    "film": "Velvia 100 X-Pro",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 22,
    "roll": "0164",
    "number": 16,
    "date": "2018-11-24",
    "subject": "AlunaGeorge",
    "active": 1,
    "venue": "The Independent",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T2",
    "comment": ""
  },
  {
    "id": 23,
    "roll": "0165",
    "number": 35,
    "date": "2018-11-30",
    "subject": "Tash Sultana",
    "active": 1,
    "venue": "Fox Theater",
    "city": "Oakland",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": "Night 2"
  },
  {
    "id": 24,
    "roll": "0166",
    "number": 28,
    "date": "2018-12-02",
    "subject": "6LACK",
    "active": 1,
    "venue": "Fox Theater",
    "city": "Oakland",
    "format": "35mm",
    "film": "Pro 400H",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 25,
    "roll": "0168",
    "number": "01",
    "date": "2018-12-04",
    "subject": "Nine Inch Nails",
    "active": 0,
    "venue": "Bill Graham Civic Auditorium",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": "Night 2"
  },
  {
    "id": 26,
    "roll": "0171",
    "number": 26,
    "date": "2018-12-16",
    "subject": "Amine",
    "active": 1,
    "venue": "Regency Ballroom",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 27,
    "roll": "0175",
    "number": 17,
    "date": "2018-12-30",
    "subject": "Red Panda",
    "active": 0,
    "venue": "Moda Center",
    "city": "Portland",
    "format": "35mm",
    "film": "Portra 400",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 28,
    "roll": "0175",
    "number": 28,
    "date": "2018-12-30",
    "subject": "Damian Lillard, Portland Trailblazers",
    "active": 1,
    "venue": "Moda Center",
    "city": "Portland",
    "format": "35mm",
    "film": "Portra 400",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 29,
    "roll": "0183",
    "number": "06",
    "date": "2019-02-02",
    "subject": "A$AP Rocky",
    "active": 0,
    "venue": "Bill Graham Civic Auditorium",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 30,
    "roll": "0185",
    "number": 24,
    "date": "2019-02-12",
    "subject": "Anderson .Paak",
    "active": 1,
    "venue": "The Masonic",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 31,
    "roll": "0187",
    "number": "01",
    "date": "2019-02-22",
    "subject": "Blueface",
    "active": 0,
    "venue": "Slim's",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 32,
    "roll": "0192",
    "number": 29,
    "date": "2019-03-11",
    "subject": "Madeintyo",
    "active": 0,
    "venue": "Slim's",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Pro 400H",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 33,
    "roll": "0199",
    "number": 31,
    "date": "2019-03-19",
    "subject": "Lil Baby",
    "active": 1,
    "venue": "The Warfield",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Pro 400H",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 34,
    "roll": "0205",
    "number": "03",
    "date": "2019-03-24",
    "subject": "Boston Celtics",
    "active": 1,
    "venue": "TD Garden",
    "city": "Boston",
    "format": "35mm",
    "film": "Portra 400",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 35,
    "roll": "0207",
    "number": 33,
    "date": "2019-03-26",
    "subject": "Kelly Zutrau, Wet",
    "active": 1,
    "venue": "Regency Ballroom",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Portra 800",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 36,
    "roll": "0208",
    "number": 16,
    "date": "2019-03-29",
    "subject": "Vince Staples",
    "active": 1,
    "venue": "Fox Theater",
    "city": "Oakland",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 37,
    "roll": "0210",
    "number": "01",
    "date": "2019-03-30",
    "subject": "Tommy Genesis",
    "active": 0,
    "venue": "Starline Social Club",
    "city": "Oakland",
    "format": "35mm",
    "film": "Portra 800",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 38,
    "roll": "0215",
    "number": 22,
    "date": "2019-04-19",
    "subject": "Jaden Smith",
    "active": 1,
    "venue": "Coachella 2019",
    "city": "Indio",
    "format": "35mm",
    "film": "Pro 400H",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 39,
    "roll": "0220",
    "number": 16,
    "date": "2019-04-21",
    "subject": "Kanye West",
    "active": 1,
    "venue": "Coachella 2019",
    "city": "Indio",
    "format": "35mm",
    "film": "Pro 400H",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 40,
    "roll": "0222",
    "number": 27,
    "date": "2019-04-21",
    "subject": "Ariana Grande",
    "active": 0,
    "venue": "Coachella 2019",
    "city": "Indio",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 41,
    "roll": "0225",
    "number": "08",
    "date": "2019-04-28",
    "subject": "Louis Futon",
    "active": 1,
    "venue": "The Independent",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Superia 400",
    "camera": "Contax T3",
    "comment": "Night 2"
  },
  {
    "id": 42,
    "roll": "0229",
    "number": 35,
    "date": "2019-05-22",
    "subject": "KnowKnow, Higher Brothers",
    "active": 0,
    "venue": "Regency Ballroom",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 42,
    "roll": "0230",
    "number": "03",
    "date": "2019-05-22",
    "subject": "KnowKnow, Higher Brothers",
    "active": 1,
    "venue": "Regency Ballroom",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 43,
    "roll": "0229",
    "number": 36,
    "date": "2019-05-22",
    "subject": "Masiwei, Higher Brothers",
    "active": 0,
    "venue": "Regency Ballroom",
    "city": "San Francisco",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 44,
    "roll": "0234",
    "number": 36,
    "date": "2019-06-01",
    "subject": "Lil B",
    "active": 1,
    "venue": "UC Theatre",
    "city": "Berkeley",
    "format": "35mm",
    "film": "Cinestill 800T",
    "camera": "Contax T3",
    "comment": ""
  },
  {
    "id": 45,
    "roll": "0247",
    "number": 25,
    "date": "2019-07-16",
    "subject": "Beck & Matt Shultz, Cage the Elephant",
    "active": 0,
    "venue": "Shoreline Amphitheatre",
    "city": "Mountain View",
    "format": "35mm",
    "film": "Portra 400",
    "camera": "Contax T3",
    "comment": ""
  }
]

export default function photoGenerator(assetHost) {
  return shuffle(makeUsablePhotoArray(photos, assetHost))
}
